name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev'
    steps:
      - name: Greeting
        run: echo "Run successfully"

  other:
    runs-on: ubuntu-latest
    steps:
      - name: Information
        run: echo ${{ github.event_name }}
      - name: More information
        run: echo ${{ github.ref }}
